#!/Users/travislawrence/perl5/perlbrew/perls/perl-5.18.2/bin/perl -w

eval 'exec /Users/travislawrence/perl5/perlbrew/perls/perl-5.18.2/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell
use POSIX;
use Getopt::Long qw(:config bundling require_order auto_version);
use Pod::Usage;
use FAST;
use FAST::Bio::SeqIO;
use FAST::Bio::PrimarySeq;
use FAST::Bio::Tools::MySeqStats;
use strict;

use vars qw($VERSION $DESC $NAME $COMMAND $DATE);
$VERSION = $FAST::VERSION; 
$DESC    = "";
$NAME    = $0;
$NAME    =~ s/^.*\///;
$COMMAND = join " ",$NAME,@ARGV;
$DATE = POSIX::strftime("%c",localtime());

use constant { true => 1, false => 0 };

## DEFAULT OPTION VALUES
my $def_format  = $FAST::DEF_FORMAT;  #7/1/13 "fasta";
my $def_logname = $FAST::DEF_LOGNAME; #7/1/13 "FAST.log.txt";

## OPTION VARIABLES
my $man                  = undef;  # --man
my $help                 = undef;  # -h
my $moltype              = undef;  # -m, in case bioperl can't tell
my $log                  = undef;        # -l
my $logname              = $def_logname; # -L
my $comment              = undef;        # -C
my $norm                 = undef; #-n
my $total                = undef; #-t
my $append               = undef; #-a
my $strict               = undef;
my $iupac                = undef;
my $case                 = undef;

my $warned;
my $job_alphabet;
my $alphabet;
my %sum;
my $filter;
my $mono;


GetOptions('help|h'         		 => \$help, 
	   'man'            		 => \$man,
	   'moltype|m=s'                 => sub{  my (undef,$val) = @_; 
						  die "$NAME: --moltype or -m option must be either \"dna\", \"rna\" or \"protein\"" 
						    unless $val =~ /dna|rna|protein/i; 
						  $moltype = $val;
						},
	   'log|l'                       => \$log,
	   'logname|L=s'                 => \$logname,
	   'comment|C=s'                 => \$comment,
     'norm|n'                      => \$norm,
     'total|t'                     => \$total,
     'append|a'                    => \$append,
     'iupac|i'                     => \$iupac,
     'strict|s'                    => \$strict,
     'ignore|c'                    => \$case,

	  ) 
  or pod2usage(2);
		  
pod2usage(1) if $help;
pod2usage(-verbose => 2) if $man;
pod2usage("$0: Requires exactly one argument (a regex) when taking input from STDIN. Try $NAME -h for help.") if ((-t STDIN) && (@ARGV != 1));
pod2usage("$0: Requires at least one argument. Try $NAME -h for help.") if (@ARGV == 0);

&FAST::log($logname, $DATE, $COMMAND, $comment) if ($log);

my %alpha_hash;
$alpha_hash{'dnastrict'}     = qr/[ACTGactg]/;
$alpha_hash{'dnaiupac'}      = qr/[ACTGactgMRWSYKVHDBXNmrwsykvhdbxn]/;
$alpha_hash{'rnastrict'}     = qr/[ACUGacug]/;
$alpha_hash{'rnaiupac'}      = qr/[ACUGacugMRWSYKVHDBXNmrwsykvhdbxn]/;
$alpha_hash{'proteinstrict'} = qr/[ACDEFGHIKLMNPQRSTVWYacdefghiklmnpqrstvwy]/;
$alpha_hash{'proteiniupac'}  = qr/[ACDEFGHIKLMNPQRSTVWYacdefghiklmnpqrstvwyBZX\.bzx\*]/; 


my $OUT = FAST::Bio::SeqIO->newFh('-format' => $def_format);
my $IN;
unless (@ARGV) {
    if ($moltype) {
	$IN = FAST::Bio::SeqIO->new(-fh => *STDIN{IO}, '-format' => $def_format, '-alphabet' => $moltype);
    }
    else {
	$IN = FAST::Bio::SeqIO->new(-fh => *STDIN{IO}, '-format' => $def_format);
    }
}

while ($IN or @ARGV) {
  
  if (@ARGV) {
    my $file = shift (@ARGV);
    unless (-e $file) {
      warn "$NAME: Could not find file $file. Skipping.\n";
      next;
    }
    elsif ($moltype) {
      $IN = FAST::Bio::SeqIO->new(-file => $file, '-format' => 'fasta', '-alphabet' => $moltype);
    }
    else {
      $IN = FAST::Bio::SeqIO->new(-file => $file, '-format' => 'fasta');
    }
  }
  
  if ($IN) { 
    while (my $seq = $IN->next_seq()) {

      if ($moltype){
        $seq->alphabet($moltype);
      }

      unless ($warned) {
      $job_alphabet and do {
        if ($seq->alphabet ne $job_alphabet) {
        warn "Sequences appear not to be of the same type.\n";
        }
        $warned = 1;
       };
      }
    
    unless ($job_alphabet) {
      $job_alphabet = $seq->alphabet;
    }
 
    $filter = qr/./; ## MATCH ANY CHARACTER
    
    $strict and do {
      $alphabet = ($seq->alphabet . "strict"); 
      $filter = $alpha_hash{$alphabet};
    };
    
    $iupac and do {
      $alphabet = ($seq->alphabet . "iupac"); 
      $filter = $alpha_hash{$alphabet};
    };
  
    my $hash_ref = FAST::Bio::Tools::MySeqStats->count_monomers($seq);

  if ($total) {
    foreach $mono (keys %$hash_ref) {
      $sum{$mono} += $$hash_ref{$mono};
    }
  } 
  elsif ($append){
    my $old_desc = $seq->desc();
    $seq->desc(join '',"$old_desc fascomp:",&print_mono($hash_ref,$seq->display_id,$filter));     
    print $OUT $seq;

  }
  else {
    &print_mono($hash_ref,$seq->display_id,$filter);
  }
    }

  }

    undef $IN;
  }

$total and do {
  &print_mono(\%sum,"",$filter);
};   


#-----------------------
sub print_mono {
#-----------------------
  my ($hashref,$id,$filterprint) = @_;
  my ($normalizer,@keys);
  my $key;
  my $allowed;
  my $append_desc;

  if ($strict or $iupac) {
    foreach $key (keys %$hashref) {
      if ($key !~ $filterprint) {
       warn "Sequence", ($id ? " $id" : '(s)'), " contained excluded character \'$key\'.\n";
      }
    }
    unless ($case) {$filterprint =~ tr/a-z\\//d;}
    $filterprint =~ /\[(.+)\]/; ## REGEXP A REGEXP
    $allowed = $1;
    @keys = split (//,$allowed);
  } 
  else {
    @keys = sort keys %$hashref;
  }
  
  if (!$append){
  print '> ';
  foreach $key (@keys) {
    printf ("%8s",$key);
  }
  print " TOTAL";
  print " // $id\n  "; ## THE TRAILING SPACES PRIME FOR THE NEXT LINE
  if ($norm) {
    foreach $key (@keys) {
      $normalizer += $$hashref{$key} ? $$hashref{$key} : 0;
    }
    foreach $key (@keys) {
      printf ("%8.3f", ($$hashref{$key} && $normalizer) ? ($$hashref{$key}/$normalizer) : 0);
    }
  } 
  else {
    foreach $key (@keys) {
      $normalizer += $$hashref{$key} ? $$hashref{$key} : 0;
      printf ("%8d", $$hashref{$key} ? $$hashref{$key} : 0);
    }
      printf ("%8d", $normalizer);
  }
  print "\n";
 }

  else{ #If append is true
    if ($norm) { #append and normalize
      foreach $key (@keys) {
      $normalizer += $$hashref{$key} ? $$hashref{$key} : 0;
      }
      foreach $key (@keys) {
      $append_desc .= sprintf ("%s:%.3f|", $key, ($$hashref{$key} && $normalizer) ? ($$hashref{$key}/$normalizer) : 0);
      }
      return $append_desc;
    }
    else{ #append abs
      foreach $key (@keys) {
      $append_desc .= sprintf ("%s:%d|",$key, $$hashref{$key} ? $$hashref{$key} : 0);
      }
      return $append_desc
    }
    

  }

}

__END__


=head1 NAME

name - what it does

=head1 SYNOPSIS

name [options] \'PERL-REGEX\' [MULTIFASTA-FILE...]

=head1 DESCRIPTION

name takes multifasta format sequence or alignment data as input,

Options specific to name:

Options general to FAST:
  -h, --help                  	 print a brief help message
  --man             	           print full documentation
  --version                         print version
  -l, --log                         create/append to logfile	
  -L, --logname=<string>            use logfile name <string>
  -C, --comment=<string>            save comment <string> to log
  --format=<format>                 use alternative format for input  
  --moltype=<[dna|rna|protein]>      specify input sequence type

=head1 INPUT AND OUTPUT

name is part of FAST, the FAST Analysis of Sequences Toolbox, based
on Bioperl. Most core FAST utilities expect input and return output in
multifasta format. Input can occur in one or more files or on
STDIN. Output occurs to STDOUT. The FAST utility B<fasconvert> can
reformat other formats to and from multifasta.

=head1 OPTIONS

=over 8

=item B<-h>,
      B<--help>

Print a brief help message and exit.

=item B<--man>

Print the manual page and exit.

=item B<--version>

Print version information and exit.

=item B<-l>,
      B<--log>

Creates, or appends to, a generic FAST logfile in the current working
directory. The logfile records date/time of execution, full command
with options and arguments, and an optional comment.

=item B<-L [string]>,
      B<--logname=[string]>

Use [string] as the name of the logfile. Default is "FAST.log.txt".

=item B<-C [string]>,
      B<--comment=[string]>

Include comment [string] in logfile. No comment is saved by default.

=item B<--format=[format]> 		  

Use alternative format for input. See man page for "fasconvert" for
allowed formats. This is for convenience; the FAST tools are designed
to exchange data in Fasta format, and "fasta" is the default format
for this tool.

=item B<-m [dna|rna|protein]>,
      B<--moltype=[dna|rna|protein]> 		  

Specify the type of sequence on input (should not be needed in most
cases, but sometimes Bioperl cannot guess and complains when
processing data).

=back

=head1 EXAMPLES

Print all sequences with "-DNA" in the ID:

=over 8

cat data.fas | fasgrep "-DNA" > data.dna.fas

=back


=back

=head1 SEE ALSO

=over 8

=item C<man perlre>

=item C<perldoc perlre>

Documentation on perl regular expressions.

=item C<man FAST>

=item C<perldoc FAST>

Introduction and cookbook for FAST

=item L<The FAST Home Page|http://compbio.ucmerced.edu/ardell/FAST>"

=back 

=head1 CITING

If you use FAST, please cite I<Ardell (2013). FAST: FAST Analysis of
Sequences Toolbox. Bioinformatics> and Bioperl I<Stajich et al.>.

=cut
